# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              frontend/src/client/.*|
              backend/app/email-templates/build/.*
          )$
      - id: trailing-whitespace
        exclude: ^frontend/src/client/.*

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.5
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --python-version=3.10]
        files: ^backend/
        additional_dependencies:
          - sqlmodel
          - pydantic
          - fastapi

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: ./node_modules/.bin/biome check --config-path=./frontend --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"

      - id: local-pytest
        name: pytest (requires docker compose db to be running)
        entry: bash scripts/run-tests-if-db-up.sh
        pass_filenames: false
        require_serial: true
        language: system
        files: ^backend/
