// This file is auto-generated by @hey-api/openapi-ts

export const BaixarEstoqueResponseSchema = {
    properties: {
        service_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Id'
        },
        items_updated: {
            type: 'integer',
            title: 'Items Updated'
        }
    },
    type: 'object',
    required: ['service_id', 'items_updated'],
    title: 'BaixarEstoqueResponse'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriaTransacaoSchema = {
    type: 'string',
    enum: ['SERVICO', 'VENDA_EQUIPAMENTO', 'RENDIMENTO', 'CAPITAL_FIXO', 'COMBUSTIVEL', 'MANUTENCAO_EQUIPAMENTO', 'MANUTENCAO_VEICULO', 'MANUTENCAO_ESCRITORIO', 'COMPRA_MATERIAL', 'MO_CLT', 'MO_DIARISTA', 'ADMIN'],
    title: 'CategoriaTransacao'
} as const;

export const CategoryDashboardItemSchema = {
    properties: {
        category: {
            '$ref': '#/components/schemas/ProductCategory'
        },
        em_estoque_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Estoque Total'
        },
        reservado_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Reservado Total'
        },
        utilizado_total: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Utilizado Total'
        }
    },
    type: 'object',
    required: ['category', 'em_estoque_total', 'reservado_total', 'utilizado_total'],
    title: 'CategoryDashboardItem'
} as const;

export const ClientCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 14,
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        bairro: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bairro'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        }
    },
    type: 'object',
    required: ['name', 'document_type', 'document_number'],
    title: 'ClientCreate'
} as const;

export const ClientPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 14,
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        bairro: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bairro'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'document_type', 'document_number', 'id'],
    title: 'ClientPublic'
} as const;

export const ClientRefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ClientRef'
} as const;

export const ClientUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        document_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DocumentType'
                },
                {
                    type: 'null'
                }
            ]
        },
        document_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        bairro: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bairro'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        state: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'State'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        }
    },
    type: 'object',
    title: 'ClientUpdate'
} as const;

export const ClientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientsPublic'
} as const;

export const CompanySettingsReadSchema = {
    properties: {
        company_name: {
            type: 'string',
            title: 'Company Name'
        },
        cnpj: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cnpj'
        },
        inscricao_municipal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inscricao Municipal'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        }
    },
    type: 'object',
    required: ['company_name'],
    title: 'CompanySettingsRead'
} as const;

export const CompanySettingsUpdateSchema = {
    properties: {
        company_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Name'
        },
        cnpj: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 18
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cnpj'
        },
        inscricao_municipal: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Inscricao Municipal'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        }
    },
    type: 'object',
    title: 'CompanySettingsUpdate'
} as const;

export const DeductionItemSchema = {
    properties: {
        service_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Item Id'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['service_item_id', 'quantity'],
    title: 'DeductionItem'
} as const;

export const DeductionSummarySchema = {
    properties: {
        product_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Item Id'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['product_item_id', 'quantity'],
    title: 'DeductionSummary'
} as const;

export const DocumentTypeSchema = {
    type: 'string',
    enum: ['cpf', 'cnpj'],
    title: 'DocumentType'
} as const;

export const FornecedorCategoryEnumSchema = {
    type: 'string',
    enum: ['tubos', 'conexoes', 'bombas', 'cabos', 'outros'],
    title: 'FornecedorCategoryEnum'
} as const;

export const FornecedorContatoCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        telefone: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Telefone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        description: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'telefone', 'description'],
    title: 'FornecedorContatoCreate'
} as const;

export const FornecedorContatoPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        telefone: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Telefone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        description: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fornecedor_id: {
            type: 'string',
            format: 'uuid',
            title: 'Fornecedor Id'
        }
    },
    type: 'object',
    required: ['name', 'telefone', 'description', 'id', 'fornecedor_id'],
    title: 'FornecedorContatoPublic'
} as const;

export const FornecedorContatoUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        telefone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telefone'
        },
        whatsapp: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'FornecedorContatoUpdate'
} as const;

export const FornecedorCreateSchema = {
    properties: {
        company_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Company Name'
        },
        cnpj: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cnpj'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/FornecedorCategoryEnum'
            },
            type: 'array',
            title: 'Categories',
            default: []
        }
    },
    type: 'object',
    required: ['company_name'],
    title: 'FornecedorCreate'
} as const;

export const FornecedorPublicSchema = {
    properties: {
        company_name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Company Name'
        },
        cnpj: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cnpj'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/FornecedorCategoryEnum'
            },
            type: 'array',
            title: 'Categories'
        },
        contatos: {
            items: {
                '$ref': '#/components/schemas/FornecedorContatoPublic'
            },
            type: 'array',
            title: 'Contatos'
        }
    },
    type: 'object',
    required: ['company_name', 'id', 'categories', 'contatos'],
    title: 'FornecedorPublic'
} as const;

export const FornecedorRefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        company_name: {
            type: 'string',
            title: 'Company Name'
        }
    },
    type: 'object',
    required: ['id', 'company_name'],
    title: 'FornecedorRef'
} as const;

export const FornecedorUpdateSchema = {
    properties: {
        company_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Name'
        },
        cnpj: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cnpj'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        categories: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/FornecedorCategoryEnum'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Categories'
        }
    },
    type: 'object',
    title: 'FornecedorUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemTypeSchema = {
    type: 'string',
    enum: ['material', 'serviço'],
    title: 'ItemType'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrcamentoCreateSchema = {
    properties: {
        service_type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        forma_pagamento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forma Pagamento'
        },
        vendedor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vendedor'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        validade_proposta: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validade Proposta'
        }
    },
    type: 'object',
    required: ['service_type', 'execution_address', 'client_id'],
    title: 'OrcamentoCreate'
} as const;

export const OrcamentoItemCreateSchema = {
    properties: {
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Quantity'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Unit Price'
        },
        show_unit_price: {
            type: 'boolean',
            title: 'Show Unit Price',
            default: true
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        }
    },
    type: 'object',
    required: ['description', 'quantity', 'unit_price', 'product_id'],
    title: 'OrcamentoItemCreate'
} as const;

export const OrcamentoItemReadSchema = {
    properties: {
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity'
        },
        unit_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price'
        },
        show_unit_price: {
            type: 'boolean',
            title: 'Show Unit Price',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orcamento_id: {
            type: 'string',
            format: 'uuid',
            title: 'Orcamento Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['description', 'quantity', 'unit_price', 'id', 'orcamento_id', 'product_id'],
    title: 'OrcamentoItemRead'
} as const;

export const OrcamentoItemUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number',
                    exclusiveMinimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quantity'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price'
        },
        show_unit_price: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Show Unit Price'
        }
    },
    type: 'object',
    title: 'OrcamentoItemUpdate'
} as const;

export const OrcamentoListReadSchema = {
    properties: {
        service_type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        forma_pagamento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forma Pagamento'
        },
        vendedor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vendedor'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ref_code: {
            type: 'string',
            title: 'Ref Code'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        status: {
            '$ref': '#/components/schemas/OrcamentoStatus'
        },
        validade_proposta: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validade Proposta'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['service_type', 'execution_address', 'id', 'ref_code', 'client_id', 'status'],
    title: 'OrcamentoListRead',
    description: 'Lightweight orçamento for list responses — no items or logs.'
} as const;

export const OrcamentoReadSchema = {
    properties: {
        service_type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        forma_pagamento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forma Pagamento'
        },
        vendedor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vendedor'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ref_code: {
            type: 'string',
            title: 'Ref Code'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        status: {
            '$ref': '#/components/schemas/OrcamentoStatus'
        },
        validade_proposta: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validade Proposta'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        items: {
            items: {
                '$ref': '#/components/schemas/OrcamentoItemRead'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        status_logs: {
            items: {
                '$ref': '#/components/schemas/OrcamentoStatusLogRead'
            },
            type: 'array',
            title: 'Status Logs',
            default: []
        }
    },
    type: 'object',
    required: ['service_type', 'execution_address', 'id', 'ref_code', 'client_id', 'status'],
    title: 'OrcamentoRead',
    description: 'Full orçamento detail — includes items and status_logs.'
} as const;

export const OrcamentoStatusSchema = {
    type: 'string',
    enum: ['rascunho', 'em_analise', 'aprovado', 'cancelado'],
    title: 'OrcamentoStatus'
} as const;

export const OrcamentoStatusLogReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        from_status: {
            '$ref': '#/components/schemas/OrcamentoStatus'
        },
        to_status: {
            '$ref': '#/components/schemas/OrcamentoStatus'
        },
        changed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By'
        },
        changed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed At'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['id', 'from_status', 'to_status'],
    title: 'OrcamentoStatusLogRead'
} as const;

export const OrcamentoTransitionRequestSchema = {
    properties: {
        to_status: {
            '$ref': '#/components/schemas/OrcamentoStatus'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['to_status'],
    title: 'OrcamentoTransitionRequest'
} as const;

export const OrcamentoTransitionResponseSchema = {
    properties: {
        orcamento: {
            '$ref': '#/components/schemas/OrcamentoRead'
        }
    },
    type: 'object',
    required: ['orcamento'],
    title: 'OrcamentoTransitionResponse'
} as const;

export const OrcamentoUpdateSchema = {
    properties: {
        service_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceType'
                },
                {
                    type: 'null'
                }
            ]
        },
        execution_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Address'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        cep: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 9
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cep'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        forma_pagamento: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Forma Pagamento'
        },
        validade_proposta: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validade Proposta'
        },
        vendedor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vendedor'
        }
    },
    type: 'object',
    title: 'OrcamentoUpdate'
} as const;

export const OrcamentosPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OrcamentoListRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OrcamentosPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProductCategorySchema = {
    type: 'string',
    enum: ['tubos', 'conexoes', 'bombas', 'cabos', 'outros'],
    title: 'ProductCategory'
} as const;

export const ProductCreateSchema = {
    properties: {
        product_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Type Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Unit Price'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['product_type_id', 'name', 'unit_price'],
    title: 'ProductCreate'
} as const;

export const ProductItemCreateSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['product_id', 'quantity'],
    title: 'ProductItemCreate'
} as const;

export const ProductItemReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        quantity: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Quantity'
        },
        status: {
            '$ref': '#/components/schemas/ProductItemStatus'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'product_id', 'quantity', 'status'],
    title: 'ProductItemRead'
} as const;

export const ProductItemStatusSchema = {
    type: 'string',
    enum: ['em_estoque', 'reservado', 'utilizado'],
    title: 'ProductItemStatus'
} as const;

export const ProductReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Type Id'
        },
        product_type: {
            '$ref': '#/components/schemas/ProductTypeRead'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        },
        fornecedor: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FornecedorRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        unit_price: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Unit Price'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'product_type_id', 'product_type', 'name', 'unit_price'],
    title: 'ProductRead'
} as const;

export const ProductTypeCreateSchema = {
    properties: {
        category: {
            '$ref': '#/components/schemas/ProductCategory'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        unit_of_measure: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Unit Of Measure'
        }
    },
    type: 'object',
    required: ['category', 'name', 'unit_of_measure'],
    title: 'ProductTypeCreate'
} as const;

export const ProductTypeReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        category: {
            '$ref': '#/components/schemas/ProductCategory'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        unit_of_measure: {
            type: 'string',
            title: 'Unit Of Measure'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'category', 'name', 'unit_of_measure'],
    title: 'ProductTypeRead'
} as const;

export const ProductTypeUpdateSchema = {
    properties: {
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProductCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        unit_of_measure: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Of Measure'
        }
    },
    type: 'object',
    title: 'ProductTypeUpdate'
} as const;

export const ProductUpdateSchema = {
    properties: {
        product_type_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Type Id'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        },
        unit_price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Price'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProductUpdate'
} as const;

export const ResumoMensalSchema = {
    properties: {
        ano: {
            type: 'integer',
            title: 'Ano'
        },
        mes: {
            type: 'integer',
            title: 'Mes'
        },
        total_receitas: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Receitas'
        },
        total_despesas: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Despesas'
        },
        resultado_liquido: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Resultado Liquido'
        }
    },
    type: 'object',
    required: ['ano', 'mes', 'total_receitas', 'total_despesas', 'resultado_liquido'],
    title: 'ResumoMensal'
} as const;

export const ServiceCreateSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        }
    },
    type: 'object',
    required: ['type', 'execution_address', 'client_id'],
    title: 'ServiceCreate'
} as const;

export const ServiceItemCreateSchema = {
    properties: {
        item_type: {
            '$ref': '#/components/schemas/ItemType'
        },
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            type: 'number',
            minimum: 0,
            title: 'Unit Price'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        }
    },
    type: 'object',
    required: ['item_type', 'description', 'quantity', 'unit_price'],
    title: 'ServiceItemCreate'
} as const;

export const ServiceItemReadSchema = {
    properties: {
        item_type: {
            '$ref': '#/components/schemas/ItemType'
        },
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            type: 'number',
            minimum: 0,
            title: 'Unit Price'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        service_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Id'
        }
    },
    type: 'object',
    required: ['item_type', 'description', 'quantity', 'unit_price', 'id', 'service_id'],
    title: 'ServiceItemRead'
} as const;

export const ServiceListReadSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        cancelled_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled Reason'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ServiceItemRead'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        has_stock_warning: {
            type: 'boolean',
            title: 'Has Stock Warning',
            default: false
        }
    },
    type: 'object',
    required: ['type', 'execution_address', 'id', 'client_id', 'status'],
    title: 'ServiceListRead',
    description: 'Lightweight service summary for list responses — omits status_logs.'
} as const;

export const ServiceReadSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        cancelled_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled Reason'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ServiceItemRead'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        status_logs: {
            items: {
                '$ref': '#/components/schemas/ServiceStatusLogRead'
            },
            type: 'array',
            title: 'Status Logs',
            default: []
        },
        has_stock_warning: {
            type: 'boolean',
            title: 'Has Stock Warning',
            default: false
        }
    },
    type: 'object',
    required: ['type', 'execution_address', 'id', 'client_id', 'status'],
    title: 'ServiceRead',
    description: 'Full service detail — includes status_logs. Used by GET /services/{id}.'
} as const;

export const ServiceStatusSchema = {
    type: 'string',
    enum: ['requested', 'scheduled', 'executing', 'completed', 'cancelled'],
    title: 'ServiceStatus'
} as const;

export const ServiceStatusLogReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        from_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        to_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        changed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By'
        },
        changed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Changed At'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        changed_by_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By Name'
        }
    },
    type: 'object',
    required: ['id', 'from_status', 'to_status', 'changed_by', 'changed_at'],
    title: 'ServiceStatusLogRead'
} as const;

export const ServiceSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        }
    },
    type: 'object',
    required: ['id', 'type', 'status'],
    title: 'ServiceSummary'
} as const;

export const ServiceTransitionRequestSchema = {
    properties: {
        to_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        deduction_items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DeductionItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deduction Items'
        }
    },
    type: 'object',
    required: ['to_status'],
    title: 'ServiceTransitionRequest'
} as const;

export const ServiceTransitionResponseSchema = {
    properties: {
        service: {
            '$ref': '#/components/schemas/ServiceRead'
        },
        stock_warnings: {
            items: {
                '$ref': '#/components/schemas/StockWarning'
            },
            type: 'array',
            title: 'Stock Warnings',
            default: []
        }
    },
    type: 'object',
    required: ['service'],
    title: 'ServiceTransitionResponse'
} as const;

export const ServiceTypeSchema = {
    type: 'string',
    enum: ['perfuração', 'reparo'],
    title: 'ServiceType'
} as const;

export const ServiceUpdateSchema = {
    properties: {
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceType'
                },
                {
                    type: 'null'
                }
            ]
        },
        execution_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ServiceUpdate'
} as const;

export const ServicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServiceListRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServicesPublic'
} as const;

export const SetPermissionsInSchema = {
    properties: {
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['permissions'],
    title: 'SetPermissionsIn'
} as const;

export const StockPredictionReadSchema = {
    properties: {
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        days_to_stockout: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Days To Stockout'
        },
        level: {
            type: 'string',
            title: 'Level'
        },
        em_estoque_qty: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Em Estoque Qty'
        },
        reservado_qty: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Reservado Qty'
        },
        avg_daily_consumption: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Daily Consumption'
        }
    },
    type: 'object',
    required: ['product_id', 'level', 'em_estoque_qty', 'reservado_qty'],
    title: 'StockPredictionRead'
} as const;

export const StockWarningSchema = {
    properties: {
        service_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Item Id'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        required_quantity: {
            type: 'number',
            title: 'Required Quantity'
        },
        available_quantity: {
            type: 'number',
            title: 'Available Quantity'
        },
        shortfall: {
            type: 'number',
            title: 'Shortfall'
        }
    },
    type: 'object',
    required: ['service_item_id', 'description', 'required_quantity', 'available_quantity', 'shortfall'],
    title: 'StockWarning'
} as const;

export const TipoTransacaoSchema = {
    type: 'string',
    enum: ['receita', 'despesa'],
    title: 'TipoTransacao'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransacaoCreateSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/TipoTransacao'
        },
        categoria: {
            '$ref': '#/components/schemas/CategoriaTransacao'
        },
        valor: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Valor'
        },
        data_competencia: {
            type: 'string',
            format: 'date',
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        }
    },
    type: 'object',
    required: ['tipo', 'categoria', 'valor', 'data_competencia'],
    title: 'TransacaoCreate'
} as const;

export const TransacaoPublicSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/TipoTransacao'
        },
        categoria: {
            '$ref': '#/components/schemas/CategoriaTransacao'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        data_competencia: {
            type: 'string',
            format: 'date',
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        },
        service: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['tipo', 'categoria', 'valor', 'data_competencia', 'id'],
    title: 'TransacaoPublic'
} as const;

export const TransacaoUpdateSchema = {
    properties: {
        categoria: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CategoriaTransacao'
                },
                {
                    type: 'null'
                }
            ]
        },
        valor: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valor'
        },
        data_competencia: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        }
    },
    type: 'object',
    title: 'TransacaoUpdate'
} as const;

export const TransacoesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TransacaoPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TransacoesPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPermissionsOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        role_defaults: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Role Defaults'
        },
        overrides: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Overrides'
        },
        effective: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Effective'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'role', 'is_superuser', 'role_defaults', 'overrides', 'effective'],
    title: 'UserPermissionsOut'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'finance', 'client'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;