// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategoriaTransacaoSchema = {
    type: 'string',
    enum: ['SERVICO', 'VENDA_EQUIPAMENTO', 'RENDIMENTO', 'CAPITAL_FIXO', 'COMBUSTIVEL', 'MANUTENCAO_EQUIPAMENTO', 'MANUTENCAO_VEICULO', 'MANUTENCAO_ESCRITORIO', 'COMPRA_MATERIAL', 'MO_CLT', 'MO_DIARISTA', 'ADMIN'],
    title: 'CategoriaTransacao'
} as const;

export const ClientCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 14,
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        }
    },
    type: 'object',
    required: ['name', 'document_type', 'document_number'],
    title: 'ClientCreate'
} as const;

export const ClientPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 14,
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'document_type', 'document_number', 'id'],
    title: 'ClientPublic'
} as const;

export const ClientRefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ClientRef'
} as const;

export const ClientUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        document_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DocumentType'
                },
                {
                    type: 'null'
                }
            ]
        },
        document_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 14
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        }
    },
    type: 'object',
    title: 'ClientUpdate'
} as const;

export const ClientsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientsPublic'
} as const;

export const DeductionItemSchema = {
    properties: {
        service_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Item Id'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['service_item_id', 'quantity'],
    title: 'DeductionItem'
} as const;

export const DocumentTypeSchema = {
    type: 'string',
    enum: ['cpf', 'cnpj'],
    title: 'DocumentType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemTypeSchema = {
    type: 'string',
    enum: ['material', 'serviço'],
    title: 'ItemType'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ResumoMensalSchema = {
    properties: {
        ano: {
            type: 'integer',
            title: 'Ano'
        },
        mes: {
            type: 'integer',
            title: 'Mes'
        },
        total_receitas: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Receitas'
        },
        total_despesas: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Total Despesas'
        },
        resultado_liquido: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Resultado Liquido'
        }
    },
    type: 'object',
    required: ['ano', 'mes', 'total_receitas', 'total_despesas', 'resultado_liquido'],
    title: 'ResumoMensal'
} as const;

export const ServiceCreateSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        }
    },
    type: 'object',
    required: ['type', 'execution_address', 'client_id'],
    title: 'ServiceCreate'
} as const;

export const ServiceItemCreateSchema = {
    properties: {
        item_type: {
            '$ref': '#/components/schemas/ItemType'
        },
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            type: 'number',
            minimum: 0,
            title: 'Unit Price'
        }
    },
    type: 'object',
    required: ['item_type', 'description', 'quantity', 'unit_price'],
    title: 'ServiceItemCreate'
} as const;

export const ServiceItemReadSchema = {
    properties: {
        item_type: {
            '$ref': '#/components/schemas/ItemType'
        },
        description: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Description'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        unit_price: {
            type: 'number',
            minimum: 0,
            title: 'Unit Price'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        service_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Id'
        }
    },
    type: 'object',
    required: ['item_type', 'description', 'quantity', 'unit_price', 'id', 'service_id'],
    title: 'ServiceItemRead'
} as const;

export const ServiceReadSchema = {
    properties: {
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        execution_address: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        client_id: {
            type: 'string',
            format: 'uuid',
            title: 'Client Id'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        cancelled_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cancelled Reason'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ServiceItemRead'
            },
            type: 'array',
            title: 'Items',
            default: []
        },
        status_logs: {
            items: {
                '$ref': '#/components/schemas/ServiceStatusLogRead'
            },
            type: 'array',
            title: 'Status Logs',
            default: []
        },
        has_stock_warning: {
            type: 'boolean',
            title: 'Has Stock Warning',
            default: false
        }
    },
    type: 'object',
    required: ['type', 'execution_address', 'id', 'client_id', 'status'],
    title: 'ServiceRead'
} as const;

export const ServiceStatusSchema = {
    type: 'string',
    enum: ['requested', 'scheduled', 'executing', 'completed', 'cancelled'],
    title: 'ServiceStatus'
} as const;

export const ServiceStatusLogReadSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        from_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        to_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        changed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By'
        },
        changed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Changed At'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        changed_by_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Changed By Name'
        }
    },
    type: 'object',
    required: ['id', 'from_status', 'to_status', 'changed_by', 'changed_at'],
    title: 'ServiceStatusLogRead'
} as const;

export const ServiceSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            '$ref': '#/components/schemas/ServiceType'
        },
        status: {
            '$ref': '#/components/schemas/ServiceStatus'
        }
    },
    type: 'object',
    required: ['id', 'type', 'status'],
    title: 'ServiceSummary'
} as const;

export const ServiceTransitionRequestSchema = {
    properties: {
        to_status: {
            '$ref': '#/components/schemas/ServiceStatus'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        deduction_items: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/DeductionItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deduction Items'
        }
    },
    type: 'object',
    required: ['to_status'],
    title: 'ServiceTransitionRequest'
} as const;

export const ServiceTransitionResponseSchema = {
    properties: {
        service: {
            '$ref': '#/components/schemas/ServiceRead'
        },
        stock_warnings: {
            items: {
                '$ref': '#/components/schemas/StockWarning'
            },
            type: 'array',
            title: 'Stock Warnings',
            default: []
        }
    },
    type: 'object',
    required: ['service'],
    title: 'ServiceTransitionResponse'
} as const;

export const ServiceTypeSchema = {
    type: 'string',
    enum: ['perfuração', 'reparo'],
    title: 'ServiceType'
} as const;

export const ServiceUpdateSchema = {
    properties: {
        type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceType'
                },
                {
                    type: 'null'
                }
            ]
        },
        execution_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Execution Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ServiceUpdate'
} as const;

export const ServicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServiceRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServicesPublic'
} as const;

export const SetPermissionsInSchema = {
    properties: {
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['permissions'],
    title: 'SetPermissionsIn'
} as const;

export const StockWarningSchema = {
    properties: {
        service_item_id: {
            type: 'string',
            format: 'uuid',
            title: 'Service Item Id'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        required_quantity: {
            type: 'number',
            title: 'Required Quantity'
        },
        available_quantity: {
            type: 'number',
            title: 'Available Quantity'
        },
        shortfall: {
            type: 'number',
            title: 'Shortfall'
        }
    },
    type: 'object',
    required: ['service_item_id', 'description', 'required_quantity', 'available_quantity', 'shortfall'],
    title: 'StockWarning'
} as const;

export const TipoTransacaoSchema = {
    type: 'string',
    enum: ['receita', 'despesa'],
    title: 'TipoTransacao'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TransacaoCreateSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/TipoTransacao'
        },
        categoria: {
            '$ref': '#/components/schemas/CategoriaTransacao'
        },
        valor: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Valor'
        },
        data_competencia: {
            type: 'string',
            format: 'date',
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        }
    },
    type: 'object',
    required: ['tipo', 'categoria', 'valor', 'data_competencia'],
    title: 'TransacaoCreate'
} as const;

export const TransacaoPublicSchema = {
    properties: {
        tipo: {
            '$ref': '#/components/schemas/TipoTransacao'
        },
        categoria: {
            '$ref': '#/components/schemas/CategoriaTransacao'
        },
        valor: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Valor'
        },
        data_competencia: {
            type: 'string',
            format: 'date',
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        },
        service: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServiceSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        client: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ClientRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['tipo', 'categoria', 'valor', 'data_competencia', 'id'],
    title: 'TransacaoPublic'
} as const;

export const TransacaoUpdateSchema = {
    properties: {
        categoria: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CategoriaTransacao'
                },
                {
                    type: 'null'
                }
            ]
        },
        valor: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Valor'
        },
        data_competencia: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Competencia'
        },
        descricao: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Descricao'
        },
        nome_contraparte: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nome Contraparte'
        },
        service_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Service Id'
        },
        fornecedor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fornecedor Id'
        }
    },
    type: 'object',
    title: 'TransacaoUpdate'
} as const;

export const TransacoesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TransacaoPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TransacoesPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPermissionsOutSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        role_defaults: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Role Defaults'
        },
        overrides: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Overrides'
        },
        effective: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Effective'
        }
    },
    type: 'object',
    required: ['id', 'email', 'full_name', 'role', 'is_superuser', 'role_defaults', 'overrides', 'effective'],
    title: 'UserPermissionsOut'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'finance', 'client'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'admin'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;