// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriaTransacao = 'SERVICO' | 'VENDA_EQUIPAMENTO' | 'RENDIMENTO' | 'CAPITAL_FIXO' | 'COMBUSTIVEL' | 'MANUTENCAO_EQUIPAMENTO' | 'MANUTENCAO_VEICULO' | 'MANUTENCAO_ESCRITORIO' | 'COMPRA_MATERIAL' | 'MO_CLT' | 'MO_DIARISTA' | 'ADMIN';

export type ClientCreate = {
    name: string;
    document_type: DocumentType;
    document_number: string;
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
};

export type ClientPublic = {
    name: string;
    document_type: DocumentType;
    document_number: string;
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ClientRef = {
    id: string;
    name: string;
};

export type ClientsPublic = {
    data: Array<ClientPublic>;
    count: number;
};

export type ClientUpdate = {
    name?: (string | null);
    document_type?: (DocumentType | null);
    document_number?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    address?: (string | null);
};

export type DeductionItem = {
    service_item_id: string;
    quantity: number;
};

export type DocumentType = 'cpf' | 'cnpj';

export type FornecedorCategoryEnum = 'tubos' | 'conexoes' | 'bombas' | 'cabos' | 'outros';

export type FornecedorContatoCreate = {
    name: string;
    telefone: string;
    whatsapp?: (string | null);
    description: string;
};

export type FornecedorContatoPublic = {
    name: string;
    telefone: string;
    whatsapp?: (string | null);
    description: string;
    id: string;
    fornecedor_id: string;
};

export type FornecedorContatoUpdate = {
    name?: (string | null);
    telefone?: (string | null);
    whatsapp?: (string | null);
    description?: (string | null);
};

export type FornecedorCreate = {
    company_name: string;
    cnpj?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    categories?: Array<FornecedorCategoryEnum>;
};

export type FornecedorPublic = {
    company_name: string;
    cnpj?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    id: string;
    categories: Array<FornecedorCategoryEnum>;
    contatos: Array<FornecedorContatoPublic>;
};

export type FornecedorUpdate = {
    company_name?: (string | null);
    cnpj?: (string | null);
    address?: (string | null);
    notes?: (string | null);
    categories?: (Array<FornecedorCategoryEnum> | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemType = 'material' | 'serviço';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ResumoMensal = {
    ano: number;
    mes: number;
    total_receitas: string;
    total_despesas: string;
    resultado_liquido: string;
};

export type ServiceCreate = {
    type: ServiceType;
    execution_address: string;
    notes?: (string | null);
    client_id: string;
};

export type ServiceItemCreate = {
    item_type: ItemType;
    description: string;
    quantity: number;
    unit_price: number;
};

export type ServiceItemRead = {
    item_type: ItemType;
    description: string;
    quantity: number;
    unit_price: number;
    id: string;
    service_id: string;
};

export type ServiceRead = {
    type: ServiceType;
    execution_address: string;
    notes?: (string | null);
    id: string;
    client_id: string;
    status: ServiceStatus;
    description?: (string | null);
    cancelled_reason?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    client?: (ClientRef | null);
    items?: Array<ServiceItemRead>;
    status_logs?: Array<ServiceStatusLogRead>;
    has_stock_warning?: boolean;
};

export type ServicesPublic = {
    data: Array<ServiceRead>;
    count: number;
};

export type ServiceStatus = 'requested' | 'scheduled' | 'executing' | 'completed' | 'cancelled';

export type ServiceStatusLogRead = {
    id: string;
    from_status: ServiceStatus;
    to_status: ServiceStatus;
    changed_by: (string | null);
    changed_at: string;
    notes?: (string | null);
    changed_by_name?: (string | null);
};

export type ServiceSummary = {
    id: string;
    type: ServiceType;
    status: ServiceStatus;
};

export type ServiceTransitionRequest = {
    to_status: ServiceStatus;
    reason?: (string | null);
    deduction_items?: (Array<DeductionItem> | null);
};

export type ServiceTransitionResponse = {
    service: ServiceRead;
    stock_warnings?: Array<StockWarning>;
};

export type ServiceType = 'perfuração' | 'reparo';

export type ServiceUpdate = {
    type?: (ServiceType | null);
    execution_address?: (string | null);
    notes?: (string | null);
    description?: (string | null);
};

export type SetPermissionsIn = {
    permissions: Array<(string)>;
};

export type StockWarning = {
    service_item_id: string;
    description: string;
    required_quantity: number;
    available_quantity: number;
    shortfall: number;
};

export type TipoTransacao = 'receita' | 'despesa';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransacaoCreate = {
    tipo: TipoTransacao;
    categoria: CategoriaTransacao;
    valor: (number | string);
    data_competencia: string;
    descricao?: (string | null);
    nome_contraparte?: (string | null);
    service_id?: (string | null);
    client_id?: (string | null);
    fornecedor_id?: (string | null);
};

export type TransacaoPublic = {
    tipo: TipoTransacao;
    categoria: CategoriaTransacao;
    valor: string;
    data_competencia: string;
    descricao?: (string | null);
    nome_contraparte?: (string | null);
    id: string;
    service_id?: (string | null);
    client_id?: (string | null);
    fornecedor_id?: (string | null);
    service?: (ServiceSummary | null);
    client?: (ClientRef | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type TransacaoUpdate = {
    categoria?: (CategoriaTransacao | null);
    valor?: (number | string | null);
    data_competencia?: (string | null);
    descricao?: (string | null);
    nome_contraparte?: (string | null);
    service_id?: (string | null);
    fornecedor_id?: (string | null);
};

export type TransacoesPublic = {
    data: Array<TransacaoPublic>;
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPermissionsOut = {
    id: string;
    email: string;
    full_name: (string | null);
    role: string;
    is_superuser: boolean;
    role_defaults: Array<(string)>;
    overrides: Array<(string)>;
    effective: Array<(string)>;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    created_at?: (string | null);
    permissions?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'admin' | 'finance' | 'client';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ClientsReadClientsData = {
    limit?: number;
    skip?: number;
};

export type ClientsReadClientsResponse = (ClientsPublic);

export type ClientsCreateClientData = {
    requestBody: ClientCreate;
};

export type ClientsCreateClientResponse = (ClientPublic);

export type ClientsReadClientData = {
    clientId: string;
};

export type ClientsReadClientResponse = (ClientPublic);

export type ClientsUpdateClientData = {
    clientId: string;
    requestBody: ClientUpdate;
};

export type ClientsUpdateClientResponse = (ClientPublic);

export type ClientsDeleteClientData = {
    clientId: string;
};

export type ClientsDeleteClientResponse = (Message);

export type FornecedoresListFornecedoresData = {
    category?: (FornecedorCategoryEnum | null);
    search?: (string | null);
};

export type FornecedoresListFornecedoresResponse = (Array<FornecedorPublic>);

export type FornecedoresCreateFornecedorData = {
    requestBody: FornecedorCreate;
};

export type FornecedoresCreateFornecedorResponse = (FornecedorPublic);

export type FornecedoresGetFornecedorData = {
    fornecedorId: string;
};

export type FornecedoresGetFornecedorResponse = (FornecedorPublic);

export type FornecedoresUpdateFornecedorData = {
    fornecedorId: string;
    requestBody: FornecedorUpdate;
};

export type FornecedoresUpdateFornecedorResponse = (FornecedorPublic);

export type FornecedoresDeleteFornecedorData = {
    fornecedorId: string;
};

export type FornecedoresDeleteFornecedorResponse = (void);

export type FornecedoresCreateContatoData = {
    fornecedorId: string;
    requestBody: FornecedorContatoCreate;
};

export type FornecedoresCreateContatoResponse = (FornecedorContatoPublic);

export type FornecedoresUpdateContatoData = {
    contatoId: string;
    fornecedorId: string;
    requestBody: FornecedorContatoUpdate;
};

export type FornecedoresUpdateContatoResponse = (FornecedorContatoPublic);

export type FornecedoresDeleteContatoData = {
    contatoId: string;
    fornecedorId: string;
};

export type FornecedoresDeleteContatoResponse = (void);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PermissionsGetAvailablePermissionsResponse = ({
    [key: string]: (string);
});

export type PermissionsGetUsersPermissionsResponse = (Array<UserPermissionsOut>);

export type PermissionsGetUserPermissionsData = {
    userId: string;
};

export type PermissionsGetUserPermissionsResponse = (UserPermissionsOut);

export type PermissionsSetUserPermissionsData = {
    requestBody: SetPermissionsIn;
    userId: string;
};

export type PermissionsSetUserPermissionsResponse = (UserPermissionsOut);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ServicesReadServicesData = {
    limit?: number;
    skip?: number;
};

export type ServicesReadServicesResponse = (ServicesPublic);

export type ServicesCreateServiceData = {
    requestBody: ServiceCreate;
};

export type ServicesCreateServiceResponse = (ServiceRead);

export type ServicesReadServiceData = {
    serviceId: string;
};

export type ServicesReadServiceResponse = (ServiceRead);

export type ServicesUpdateServiceData = {
    requestBody: ServiceUpdate;
    serviceId: string;
};

export type ServicesUpdateServiceResponse = (ServiceRead);

export type ServicesDeleteServiceData = {
    serviceId: string;
};

export type ServicesDeleteServiceResponse = (void);

export type ServicesTransitionServiceData = {
    requestBody: ServiceTransitionRequest;
    serviceId: string;
};

export type ServicesTransitionServiceResponse = (ServiceTransitionResponse);

export type ServicesDeductStockData = {
    serviceId: string;
};

export type ServicesDeductStockResponse = (Array<{
    [key: string]: unknown;
}>);

export type ServicesCreateServiceItemData = {
    requestBody: ServiceItemCreate;
    serviceId: string;
};

export type ServicesCreateServiceItemResponse = (ServiceItemRead);

export type ServicesDeleteServiceItemData = {
    itemId: string;
    serviceId: string;
};

export type ServicesDeleteServiceItemResponse = (void);

export type TransacoesGetResumoMensalData = {
    ano?: number;
    mes?: number;
};

export type TransacoesGetResumoMensalResponse = (ResumoMensal);

export type TransacoesReadTransacoesData = {
    categoria?: (CategoriaTransacao | null);
    dataFim?: (string | null);
    dataInicio?: (string | null);
    limit?: number;
    serviceId?: (string | null);
    skip?: number;
    tipo?: (TipoTransacao | null);
};

export type TransacoesReadTransacoesResponse = (TransacoesPublic);

export type TransacoesCreateTransacaoData = {
    requestBody: TransacaoCreate;
};

export type TransacoesCreateTransacaoResponse = (TransacaoPublic);

export type TransacoesReadTransacaoData = {
    transacaoId: string;
};

export type TransacoesReadTransacaoResponse = (TransacaoPublic);

export type TransacoesUpdateTransacaoData = {
    requestBody: TransacaoUpdate;
    transacaoId: string;
};

export type TransacoesUpdateTransacaoResponse = (TransacaoPublic);

export type TransacoesDeleteTransacaoData = {
    transacaoId: string;
};

export type TransacoesDeleteTransacaoResponse = (void);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);