/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutServicesRouteImport } from './routes/_layout/services'
import { Route as LayoutPermissionsRouteImport } from './routes/_layout/permissions'
import { Route as LayoutClientsRouteImport } from './routes/_layout/clients'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutOrcamentosIndexRouteImport } from './routes/_layout/orcamentos/index'
import { Route as LayoutFornecedoresIndexRouteImport } from './routes/_layout/fornecedores/index'
import { Route as LayoutFinanceiroIndexRouteImport } from './routes/_layout/financeiro/index'
import { Route as LayoutEstoqueIndexRouteImport } from './routes/_layout/estoque/index'
import { Route as LayoutOrcamentosNewRouteImport } from './routes/_layout/orcamentos/new'
import { Route as LayoutFornecedoresFornecedorIdRouteImport } from './routes/_layout/fornecedores/$fornecedorId'
import { Route as LayoutFinanceiroTransacoesRouteImport } from './routes/_layout/financeiro/transacoes'
import { Route as LayoutFinanceiroContasAReceberRouteImport } from './routes/_layout/financeiro/contas-a-receber'
import { Route as LayoutFinanceiroContasAPagarRouteImport } from './routes/_layout/financeiro/contas-a-pagar'
import { Route as LayoutOrcamentosOrcamentoIdIndexRouteImport } from './routes/_layout/orcamentos/$orcamentoId/index'
import { Route as LayoutEstoqueProdutosIndexRouteImport } from './routes/_layout/estoque/produtos/index'
import { Route as LayoutEstoqueProdutosNewRouteImport } from './routes/_layout/estoque/produtos/new'
import { Route as LayoutEstoqueProdutosProductIdIndexRouteImport } from './routes/_layout/estoque/produtos/$productId/index'
import { Route as LayoutEstoqueProdutosProductIdEditRouteImport } from './routes/_layout/estoque/produtos/$productId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesRoute = LayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPermissionsRoute = LayoutPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsRoute = LayoutClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrcamentosIndexRoute = LayoutOrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFornecedoresIndexRoute = LayoutFornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceiroIndexRoute = LayoutFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEstoqueIndexRoute = LayoutEstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrcamentosNewRoute = LayoutOrcamentosNewRouteImport.update({
  id: '/orcamentos/new',
  path: '/orcamentos/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFornecedoresFornecedorIdRoute =
  LayoutFornecedoresFornecedorIdRouteImport.update({
    id: '/fornecedores/$fornecedorId',
    path: '/fornecedores/$fornecedorId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinanceiroTransacoesRoute =
  LayoutFinanceiroTransacoesRouteImport.update({
    id: '/financeiro/transacoes',
    path: '/financeiro/transacoes',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinanceiroContasAReceberRoute =
  LayoutFinanceiroContasAReceberRouteImport.update({
    id: '/financeiro/contas-a-receber',
    path: '/financeiro/contas-a-receber',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFinanceiroContasAPagarRoute =
  LayoutFinanceiroContasAPagarRouteImport.update({
    id: '/financeiro/contas-a-pagar',
    path: '/financeiro/contas-a-pagar',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutOrcamentosOrcamentoIdIndexRoute =
  LayoutOrcamentosOrcamentoIdIndexRouteImport.update({
    id: '/orcamentos/$orcamentoId/',
    path: '/orcamentos/$orcamentoId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEstoqueProdutosIndexRoute =
  LayoutEstoqueProdutosIndexRouteImport.update({
    id: '/estoque/produtos/',
    path: '/estoque/produtos/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEstoqueProdutosNewRoute =
  LayoutEstoqueProdutosNewRouteImport.update({
    id: '/estoque/produtos/new',
    path: '/estoque/produtos/new',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEstoqueProdutosProductIdIndexRoute =
  LayoutEstoqueProdutosProductIdIndexRouteImport.update({
    id: '/estoque/produtos/$productId/',
    path: '/estoque/produtos/$productId/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEstoqueProdutosProductIdEditRoute =
  LayoutEstoqueProdutosProductIdEditRouteImport.update({
    id: '/estoque/produtos/$productId/edit',
    path: '/estoque/produtos/$productId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/clients': typeof LayoutClientsRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/services': typeof LayoutServicesRoute
  '/settings': typeof LayoutSettingsRoute
  '/financeiro/contas-a-pagar': typeof LayoutFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof LayoutFinanceiroContasAReceberRoute
  '/financeiro/transacoes': typeof LayoutFinanceiroTransacoesRoute
  '/fornecedores/$fornecedorId': typeof LayoutFornecedoresFornecedorIdRoute
  '/orcamentos/new': typeof LayoutOrcamentosNewRoute
  '/estoque/': typeof LayoutEstoqueIndexRoute
  '/financeiro/': typeof LayoutFinanceiroIndexRoute
  '/fornecedores/': typeof LayoutFornecedoresIndexRoute
  '/orcamentos/': typeof LayoutOrcamentosIndexRoute
  '/estoque/produtos/new': typeof LayoutEstoqueProdutosNewRoute
  '/estoque/produtos/': typeof LayoutEstoqueProdutosIndexRoute
  '/orcamentos/$orcamentoId/': typeof LayoutOrcamentosOrcamentoIdIndexRoute
  '/estoque/produtos/$productId/edit': typeof LayoutEstoqueProdutosProductIdEditRoute
  '/estoque/produtos/$productId/': typeof LayoutEstoqueProdutosProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/clients': typeof LayoutClientsRoute
  '/permissions': typeof LayoutPermissionsRoute
  '/services': typeof LayoutServicesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/financeiro/contas-a-pagar': typeof LayoutFinanceiroContasAPagarRoute
  '/financeiro/contas-a-receber': typeof LayoutFinanceiroContasAReceberRoute
  '/financeiro/transacoes': typeof LayoutFinanceiroTransacoesRoute
  '/fornecedores/$fornecedorId': typeof LayoutFornecedoresFornecedorIdRoute
  '/orcamentos/new': typeof LayoutOrcamentosNewRoute
  '/estoque': typeof LayoutEstoqueIndexRoute
  '/financeiro': typeof LayoutFinanceiroIndexRoute
  '/fornecedores': typeof LayoutFornecedoresIndexRoute
  '/orcamentos': typeof LayoutOrcamentosIndexRoute
  '/estoque/produtos/new': typeof LayoutEstoqueProdutosNewRoute
  '/estoque/produtos': typeof LayoutEstoqueProdutosIndexRoute
  '/orcamentos/$orcamentoId': typeof LayoutOrcamentosOrcamentoIdIndexRoute
  '/estoque/produtos/$productId/edit': typeof LayoutEstoqueProdutosProductIdEditRoute
  '/estoque/produtos/$productId': typeof LayoutEstoqueProdutosProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/clients': typeof LayoutClientsRoute
  '/_layout/permissions': typeof LayoutPermissionsRoute
  '/_layout/services': typeof LayoutServicesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/financeiro/contas-a-pagar': typeof LayoutFinanceiroContasAPagarRoute
  '/_layout/financeiro/contas-a-receber': typeof LayoutFinanceiroContasAReceberRoute
  '/_layout/financeiro/transacoes': typeof LayoutFinanceiroTransacoesRoute
  '/_layout/fornecedores/$fornecedorId': typeof LayoutFornecedoresFornecedorIdRoute
  '/_layout/orcamentos/new': typeof LayoutOrcamentosNewRoute
  '/_layout/estoque/': typeof LayoutEstoqueIndexRoute
  '/_layout/financeiro/': typeof LayoutFinanceiroIndexRoute
  '/_layout/fornecedores/': typeof LayoutFornecedoresIndexRoute
  '/_layout/orcamentos/': typeof LayoutOrcamentosIndexRoute
  '/_layout/estoque/produtos/new': typeof LayoutEstoqueProdutosNewRoute
  '/_layout/estoque/produtos/': typeof LayoutEstoqueProdutosIndexRoute
  '/_layout/orcamentos/$orcamentoId/': typeof LayoutOrcamentosOrcamentoIdIndexRoute
  '/_layout/estoque/produtos/$productId/edit': typeof LayoutEstoqueProdutosProductIdEditRoute
  '/_layout/estoque/produtos/$productId/': typeof LayoutEstoqueProdutosProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/clients'
    | '/permissions'
    | '/services'
    | '/settings'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/transacoes'
    | '/fornecedores/$fornecedorId'
    | '/orcamentos/new'
    | '/estoque/'
    | '/financeiro/'
    | '/fornecedores/'
    | '/orcamentos/'
    | '/estoque/produtos/new'
    | '/estoque/produtos/'
    | '/orcamentos/$orcamentoId/'
    | '/estoque/produtos/$productId/edit'
    | '/estoque/produtos/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/clients'
    | '/permissions'
    | '/services'
    | '/settings'
    | '/'
    | '/financeiro/contas-a-pagar'
    | '/financeiro/contas-a-receber'
    | '/financeiro/transacoes'
    | '/fornecedores/$fornecedorId'
    | '/orcamentos/new'
    | '/estoque'
    | '/financeiro'
    | '/fornecedores'
    | '/orcamentos'
    | '/estoque/produtos/new'
    | '/estoque/produtos'
    | '/orcamentos/$orcamentoId'
    | '/estoque/produtos/$productId/edit'
    | '/estoque/produtos/$productId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/clients'
    | '/_layout/permissions'
    | '/_layout/services'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/financeiro/contas-a-pagar'
    | '/_layout/financeiro/contas-a-receber'
    | '/_layout/financeiro/transacoes'
    | '/_layout/fornecedores/$fornecedorId'
    | '/_layout/orcamentos/new'
    | '/_layout/estoque/'
    | '/_layout/financeiro/'
    | '/_layout/fornecedores/'
    | '/_layout/orcamentos/'
    | '/_layout/estoque/produtos/new'
    | '/_layout/estoque/produtos/'
    | '/_layout/orcamentos/$orcamentoId/'
    | '/_layout/estoque/produtos/$productId/edit'
    | '/_layout/estoque/produtos/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services': {
      id: '/_layout/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LayoutServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/permissions': {
      id: '/_layout/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof LayoutPermissionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients': {
      id: '/_layout/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof LayoutClientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orcamentos/': {
      id: '/_layout/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof LayoutOrcamentosIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fornecedores/': {
      id: '/_layout/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof LayoutFornecedoresIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/financeiro/': {
      id: '/_layout/financeiro/'
      path: '/financeiro'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof LayoutFinanceiroIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/estoque/': {
      id: '/_layout/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof LayoutEstoqueIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orcamentos/new': {
      id: '/_layout/orcamentos/new'
      path: '/orcamentos/new'
      fullPath: '/orcamentos/new'
      preLoaderRoute: typeof LayoutOrcamentosNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fornecedores/$fornecedorId': {
      id: '/_layout/fornecedores/$fornecedorId'
      path: '/fornecedores/$fornecedorId'
      fullPath: '/fornecedores/$fornecedorId'
      preLoaderRoute: typeof LayoutFornecedoresFornecedorIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/financeiro/transacoes': {
      id: '/_layout/financeiro/transacoes'
      path: '/financeiro/transacoes'
      fullPath: '/financeiro/transacoes'
      preLoaderRoute: typeof LayoutFinanceiroTransacoesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/financeiro/contas-a-receber': {
      id: '/_layout/financeiro/contas-a-receber'
      path: '/financeiro/contas-a-receber'
      fullPath: '/financeiro/contas-a-receber'
      preLoaderRoute: typeof LayoutFinanceiroContasAReceberRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/financeiro/contas-a-pagar': {
      id: '/_layout/financeiro/contas-a-pagar'
      path: '/financeiro/contas-a-pagar'
      fullPath: '/financeiro/contas-a-pagar'
      preLoaderRoute: typeof LayoutFinanceiroContasAPagarRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orcamentos/$orcamentoId/': {
      id: '/_layout/orcamentos/$orcamentoId/'
      path: '/orcamentos/$orcamentoId'
      fullPath: '/orcamentos/$orcamentoId/'
      preLoaderRoute: typeof LayoutOrcamentosOrcamentoIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/estoque/produtos/': {
      id: '/_layout/estoque/produtos/'
      path: '/estoque/produtos'
      fullPath: '/estoque/produtos/'
      preLoaderRoute: typeof LayoutEstoqueProdutosIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/estoque/produtos/new': {
      id: '/_layout/estoque/produtos/new'
      path: '/estoque/produtos/new'
      fullPath: '/estoque/produtos/new'
      preLoaderRoute: typeof LayoutEstoqueProdutosNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/estoque/produtos/$productId/': {
      id: '/_layout/estoque/produtos/$productId/'
      path: '/estoque/produtos/$productId'
      fullPath: '/estoque/produtos/$productId/'
      preLoaderRoute: typeof LayoutEstoqueProdutosProductIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/estoque/produtos/$productId/edit': {
      id: '/_layout/estoque/produtos/$productId/edit'
      path: '/estoque/produtos/$productId/edit'
      fullPath: '/estoque/produtos/$productId/edit'
      preLoaderRoute: typeof LayoutEstoqueProdutosProductIdEditRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutClientsRoute: typeof LayoutClientsRoute
  LayoutPermissionsRoute: typeof LayoutPermissionsRoute
  LayoutServicesRoute: typeof LayoutServicesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutFinanceiroContasAPagarRoute: typeof LayoutFinanceiroContasAPagarRoute
  LayoutFinanceiroContasAReceberRoute: typeof LayoutFinanceiroContasAReceberRoute
  LayoutFinanceiroTransacoesRoute: typeof LayoutFinanceiroTransacoesRoute
  LayoutFornecedoresFornecedorIdRoute: typeof LayoutFornecedoresFornecedorIdRoute
  LayoutOrcamentosNewRoute: typeof LayoutOrcamentosNewRoute
  LayoutEstoqueIndexRoute: typeof LayoutEstoqueIndexRoute
  LayoutFinanceiroIndexRoute: typeof LayoutFinanceiroIndexRoute
  LayoutFornecedoresIndexRoute: typeof LayoutFornecedoresIndexRoute
  LayoutOrcamentosIndexRoute: typeof LayoutOrcamentosIndexRoute
  LayoutEstoqueProdutosNewRoute: typeof LayoutEstoqueProdutosNewRoute
  LayoutEstoqueProdutosIndexRoute: typeof LayoutEstoqueProdutosIndexRoute
  LayoutOrcamentosOrcamentoIdIndexRoute: typeof LayoutOrcamentosOrcamentoIdIndexRoute
  LayoutEstoqueProdutosProductIdEditRoute: typeof LayoutEstoqueProdutosProductIdEditRoute
  LayoutEstoqueProdutosProductIdIndexRoute: typeof LayoutEstoqueProdutosProductIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutClientsRoute: LayoutClientsRoute,
  LayoutPermissionsRoute: LayoutPermissionsRoute,
  LayoutServicesRoute: LayoutServicesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutFinanceiroContasAPagarRoute: LayoutFinanceiroContasAPagarRoute,
  LayoutFinanceiroContasAReceberRoute: LayoutFinanceiroContasAReceberRoute,
  LayoutFinanceiroTransacoesRoute: LayoutFinanceiroTransacoesRoute,
  LayoutFornecedoresFornecedorIdRoute: LayoutFornecedoresFornecedorIdRoute,
  LayoutOrcamentosNewRoute: LayoutOrcamentosNewRoute,
  LayoutEstoqueIndexRoute: LayoutEstoqueIndexRoute,
  LayoutFinanceiroIndexRoute: LayoutFinanceiroIndexRoute,
  LayoutFornecedoresIndexRoute: LayoutFornecedoresIndexRoute,
  LayoutOrcamentosIndexRoute: LayoutOrcamentosIndexRoute,
  LayoutEstoqueProdutosNewRoute: LayoutEstoqueProdutosNewRoute,
  LayoutEstoqueProdutosIndexRoute: LayoutEstoqueProdutosIndexRoute,
  LayoutOrcamentosOrcamentoIdIndexRoute: LayoutOrcamentosOrcamentoIdIndexRoute,
  LayoutEstoqueProdutosProductIdEditRoute:
    LayoutEstoqueProdutosProductIdEditRoute,
  LayoutEstoqueProdutosProductIdIndexRoute:
    LayoutEstoqueProdutosProductIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
