name: Labels
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

      # For label-checker
      - labeled
      - unlabeled

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-slim
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
